<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(ArcGISProAddInTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>CA1416</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArcGisProBridgeContracts\ArcGisProBridgeContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Config.daml" />
    <Content Include="Config.daml" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ArcGIS.Core">
      <HintPath>$(ArcGISProBinDir)ArcGIS.Core.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Core">
      <HintPath>$(ArcGISProBinDir)Extensions\Core\ArcGIS.Desktop.Core.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Framework">
      <HintPath>$(ArcGISProBinDir)ArcGIS.Desktop.Framework.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Mapping">
      <HintPath>$(ArcGISProBinDir)Extensions\Mapping\ArcGIS.Desktop.Mapping.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Layouts">
      <HintPath>$(ArcGISProBinDir)Extensions\Layout\ArcGIS.Desktop.Layouts.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Catalog">
      <HintPath>$(ArcGISProBinDir)Extensions\Catalog\ArcGIS.Desktop.Catalog.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Import Project="$(ArcGISProBinDir)Esri.ProApp.SDK.Desktop.targets" Condition="'$(MSBuildRuntimeType)' != 'Core' AND Exists('$(ArcGISProBinDir)Esri.ProApp.SDK.Desktop.targets') AND !Exists('Esri.ArcGISPro.Extensions.targets')" />
</Project>
